insert into books (id, title, publishDate, author, page, coverImage) values (1,'No Highway','1971-01-13', 'Dr. Clarissa Dibbert', 36,'http://lorempixel.com/35/50/business/');
insert into books (id, title, publishDate, author, page, coverImage) values (2,'Whats Become of Waring','1982-05-08', 'Zander Kub', 78,'http://lorempixel.com/35/50/sports/');
insert into books (id, title, publishDate, author, page, coverImage) values (3,'Where Angels Fear to Tread','1972-06-17', 'Vince Schiller MD', 22,'http://lorempixel.com/35/50/city/');
insert into books (id, title, publishDate, author, page, coverImage) values (4,'Many Waters','1953-05-19', 'Aubrey King DDS', 57,'http://lorempixel.com/35/50/nightlife/');
insert into books (id, title, publishDate, author, page, coverImage) values (5,'A Monstrous Regiment of Women','1978-09-29', 'Lauriane Barton', 94,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (6,'Consider the Lilies','1983-04-15', 'Twila Krajcik', 36,'http://lorempixel.com/35/50/nature/');
insert into books (id, title, publishDate, author, page, coverImage) values (7,'Consider the Lilies','1971-04-20', 'Sandra Stamm', 23,'http://lorempixel.com/35/50/technics/');
insert into books (id, title, publishDate, author, page, coverImage) values (8,'Some Buried Caesar','1970-04-30', 'Mr. Sabrina Mills', 67,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (9,'The Yellow Meads of Asphodel','1966-10-18', 'Eliza Bartell', 88,'http://lorempixel.com/35/50/people/');
insert into books (id, title, publishDate, author, page, coverImage) values (10,'For a Breath I Tarry','1974-12-14', 'Dr. Althea Pfeffer', 32,'http://lorempixel.com/35/50/people/');
insert into books (id, title, publishDate, author, page, coverImage) values (11,'Have His Carcase','1994-01-23', 'Dorcas Braun', 54,'http://lorempixel.com/35/50/sports/');
insert into books (id, title, publishDate, author, page, coverImage) values (12,'Blithe Spirit','1962-10-10', 'Marley Schaefer', 24,'http://lorempixel.com/35/50/fashion/');
insert into books (id, title, publishDate, author, page, coverImage) values (13,'Edna O Brien','1972-08-21', 'Brooks Breitenberg', 00,'http://lorempixel.com/35/50/sports/');
insert into books (id, title, publishDate, author, page, coverImage) values (14,'I Sing the Body Electric','1968-03-26', 'Ramiro Bednar V', 94,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (15,'Number the Stars','1974-03-01', 'Dr. Reece Koelpin', 34,'http://lorempixel.com/35/50/animals/');
insert into books (id, title, publishDate, author, page, coverImage) values (16,'A Passage to India','1990-02-03', 'Rylan Hirthe', 89,'http://lorempixel.com/35/50/fashion/');
insert into books (id, title, publishDate, author, page, coverImage) values (17,'A Many-Splendoured Thing','1956-03-12', 'Janessa Mueller', 21,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (18,'From Here to Eternity','1967-09-06', 'Edgar Littel', 01,'http://lorempixel.com/35/50/transport/');
insert into books (id, title, publishDate, author, page, coverImage) values (19,'The Soldiers Art','1965-07-19', 'Dr. Greta Nader', 67,'http://lorempixel.com/35/50/animals/');
insert into books (id, title, publishDate, author, page, coverImage) values (20,'Time To Murder And Create','1953-06-30', 'Isaiah Gottlieb', 86,'http://lorempixel.com/35/50/business/');
insert into books (id, title, publishDate, author, page, coverImage) values (21,'The Little Foxes','1969-03-23', 'Kaela Littel', 37,'http://lorempixel.com/35/50/sports/');
insert into books (id, title, publishDate, author, page, coverImage) values (22,'Brandy of the Damned','1992-11-20', 'Dr. Michale Labadie', 10,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (23,'Consider Phlebas','1968-10-10', 'Letitia Macejkovic', 14,'http://lorempixel.com/35/50/sports/');
insert into books (id, title, publishDate, author, page, coverImage) values (24,'Death Be Not Proud','1963-11-12', 'Neal Leuschke', 14,'http://lorempixel.com/35/50/city/');
insert into books (id, title, publishDate, author, page, coverImage) values (25,'Its a Battlefield','1984-08-13', 'Percival Spencer', 95,'http://lorempixel.com/35/50/people/');
insert into books (id, title, publishDate, author, page, coverImage) values (26,'By Grand Central Station I Sat Down and Wept','1952-05-19', 'Celestino Jaskolski', 20,'http://lorempixel.com/35/50/food/');
insert into books (id, title, publishDate, author, page, coverImage) values (27,'The Green Bay Tree','1969-06-17', 'Pete OKon', 55,'http://lorempixel.com/35/50/cats/');
insert into books (id, title, publishDate, author, page, coverImage) values (28,'All Passion Spent','1991-12-09', 'Michelle Keebler', 94,'http://lorempixel.com/35/50/business/');
insert into books (id, title, publishDate, author, page, coverImage) values (29,'The Little Foxes','1977-11-17', 'Eric Jakubowski', 87,'http://lorempixel.com/35/50/fashion/');
insert into books (id, title, publishDate, author, page, coverImage) values (30,'Recalled to Life','1974-03-20', 'Cynthia Cole', 87,'http://lorempixel.com/35/50/business/');